services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - APP_NAME=${APP_NAME}
        - USERNAME=${USERNAME}
    volumes:
      - ../../:/workspace:cached
    command: sleep infinity
